name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubunto-latest

    steps:
      - name: Checkout
        uses: action/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile

      - name: Build Storybook
        run: yarn build-storybook

      - name: Deply Storybook
        run: yarn deploy-storybook -- --install --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
